lint_module = dnssync_nc

[linter.disable]
src.dnssync_nc.FriendlyArgumentParser:*:*

*:*:missing-module-docstring
*:*:missing-class-docstring
*:*:invalid-name
*:*:duplicate-code
*:*:too-few-public-methods
*:*:superfluous-parens
*:*:too-many-arguments
*:*:protected-access
*:*:multiple-statements
*:*:too-many-branches
*:*:too-many-public-methods
*:*:attribute-defined-outside-init
*:*:unspecified-encoding
*:*:unused-variable
*:*:fixme
*:*:unused-argument
*:*:too-many-instance-attributes
*:*:no-else-return
*:*:arguments-renamed
*:*:redefined-outer-name
*:*:too-many-locals
*:*:no-else-raise
*:*:broad-except
*:*:too-many-nested-blocks
*:*:useless-super-delegation
*:*:consider-using-max-builtin

[linter.enable]
*:*:unused-import
*:*:raise-missing-from
*:*:anomalous-backslash-in-string
*:*:wrong-import-order
*:*:inconsistent-return-statements
*:*:logging-fstring-interpolation
*:*:f-string-without-interpolation
*:*:consider-using-max-builtin
*:*:subprocess-run-check

# vim:syntax=dosini
